# Generated by Django 2.2.6 on 2020-12-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20201207_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AddField(
            model_name='publisher',
            name='foundation_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='pub_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publisher',
            name='pub_city',
            field=models.TextField(default=''),
        ),
    ]
