# Generated by Django 2.2.6 on 2020-12-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20201207_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='book_publisher', to='p_library.Publisher'),
        ),
    ]
