# Generated by Django 2.2.6 on 2020-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20201207_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='foundation_year',
            field=models.SmallIntegerField(),
        ),
    ]
