# Generated by Django 2.2.6 on 2020-12-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_auto_20201207_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='pub_address',
            new_name='pub_site',
        ),
    ]
